name: Go Tests and Lint
on:
  push:
    branches:
      - main  # Adjust this branch name if necessary
  pull_request:
    branches:
      - main

jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Replace with your desired Go version (e.g., 1.16)

      - name: Run Go Tests
        run: go test ./...
        
      - name: Run golangci-lint
       # You may pin to the exact commit or the version.
       # uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          # version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true
